services:
  mysql:
    image: mysql:8.0
    volumes:
      - create_myblog-db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${NAME}"
      MYSQL_USER: "${USER}"

  django:
    build: .
    command: /bin/bash
    volumes:
      - .:/home/soto
    ports:
      - 127.0.0.1:8000:8000
    tty: true
    depends_on:
      - mysql

volumes:
  create_myblog-db:
