# Generated by Django 4.2.16 on 2024-09-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image_file_article_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='No comment', max_length=200),
        ),
    ]
